# Use Python3 standard environment
runtime: python311
env: standard

# Run gunicorn on app object in app.py
entrypoint: gunicorn -b :$PORT app:app

handlers:
  # This configures Google App Engine to serve the files in the app's static
  # directory.
- url: /static
  static_dir: static

  # This handler routes all requests not caught above to your main app. It is
  # required when static routes are defined, but can be omitted (along with
  # the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto

# Spin up 2 instances
manual_scaling:
  instances: 2

# Use an f1-micro machine type
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
